version: '3'

services:
  db:
    container_name: payment-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    build: 
      context: ./
      dockerfile: Dockerfile.db
    image: murilohenzo/postgres_db
    networks:
      - payments
    ports:
      - 5432:5432
  api:
    container_name: microservice-payment
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    image: murilohenzo/microservice-payment
    # entrypoint: dockerize -wait tcp://db:5432 -timeout 30s 
    depends_on:
      - db
    command: yarn dev
    networks:
      - payments
    ports:
      - 3333:3333
    environment:
      DB_HOST: db
    links:
      - db
networks:
  payments:
    driver: bridge