version: '3'

services:
  db:
    container_name: payment-db
    restart: always
    build: 
      context: /.
      dockerfile: Dockerfile.db
    image: murilohenzo/postgres_db
  api:
    container_name: microservice-payment
    build: 
      context: ./
      dockerfile: Dockerfile
    image: murilohenzo/nodejs-api
    entrypoint: dockerize -wait tcp://db:5432 -timeout 30s 
    depends_on:
      - db
    command: yarn dev
    ports:
      - 3333:3333
    environment:
      DB_HOST: db
    links:
      - db